### PR TITLE
update react and fix deprecation warnings

### LINKED ISSUE #8: Multiples deprecation warning with React 0.12
Console output when using this component: 

```
Warning: React.PropTypes.renderable will be deprecated in a future version. Use React.PropTypes.node instead.
client.js:13865 Warning: transferPropsTo is deprecated. See http://fb.me/react-transferpropsto for more information.
client.js:13865 Warning: React.renderComponent will be deprecated in a future version. Use React.render instead.
```

I will certainly provide a PR in a few days

### PR DESCRIPTION
**Pull request by nelix**
* Replace React.PropTypes.renderable with React.PropTypes.node
* Use React.createElement (fixes transferPropsTo warning, and React.DOM.iframe warning)
* Use React.render
* Update peerDependencies to work any version less than 1

fixes #8

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -14,23 +14,24 @@ var Frame = React.createClass({
...
+  } else {
+    setTimeout(this.renderFrameContents, 0);
   }
+},
+componentDidUpdate: function() {
+  this.renderFrameContents();
+},
+componentWillUnmount: function() {
+  React.unmountComponentAtNode(this.getDOMNode().contentDocument.body);
+}
```
Comment (ryanseddon) [inline index.js]: Your indentation seems off in this file can you fix that up please.

File: package.json [hunk 2]
```diff
@@ -30,11 +30,11 @@
     "karma-phantomjs-launcher": "^0.1.4",
     "es5-shim": "^3.3.0",
     "browserify": "^4.1.11",
-    "react": ">=0.11.1",
+    "react": ">= 0.12.1 < 1",
```
Comment (ryanseddon) [inline package.json]: What's the advantage of using this format over `>=0.12.1`?

**Comment by ryanseddon** [comment]
Can you update `Frame_spec.js` to use `React.render` over `React.renderComponent` too, seeing the warning in travisci build.

File: package.json (hunk 2 above)
Comment (nelix) [inline package.json]: My thinking was that anything greater than 0.* might break, but then since its under version one I guess even minor changes might break...

**Comment by nelix** [comment]
Yep, I'll take a look!

**Comment by nelix** [comment]
Hows that?

**Comment by nelix** [comment]
There are more warnings in the tests due to (I think) reactify... but I'm out of time for now.

**Comment by ryanseddon** [comment]
No worries I'll take a look this afternoon, thanks!
